# Generated by Django 4.2 on 2023-10-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IotApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, default=23, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='uid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
