# Generated by Django 4.2 on 2023-10-31 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IotApp', '0002_device_id_alter_device_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humidityreading',
            old_name='device',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='temperaturereading',
            old_name='device',
            new_name='uid',
        ),
    ]
