# Generated by Django 4.2 on 2023-10-31 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IotApp', '0003_rename_device_humidityreading_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidityreading',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IotApp.device', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='temperaturereading',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IotApp.device', to_field='uid'),
        ),
    ]
